In [1]:
# Importing the required packages 
import numpy as np 
import pandas as pd 
from sklearn.metrics import confusion_matrix 
from sklearn.model_selection import train_test_split 
from sklearn.tree import DecisionTreeClassifier 
from sklearn.metrics import accuracy_score 
from sklearn.metrics import classification_report

In [2]:
# Function importing Dataset 
def importdata(): 
    balance_data = pd.read_csv( 
'https://archive.ics.uci.edu/ml/machine-learning-'+
'databases/balance-scale/balance-scale.data', 
    sep= ',', header = None) 
      
    # Printing the dataswet shape 
    print ("Dataset Length: ", len(balance_data)) 
    print ("Dataset Shape: ", balance_data.shape) 
      
    # Printing the dataset obseravtions 
    print ("Dataset: ",balance_data.head()) 
    return balance_data

In [3]:
importdata()

Dataset Length:  625
Dataset Shape:  (625, 5)
Dataset:     0  1  2  3  4
0  B  1  1  1  1
1  R  1  1  1  2
2  R  1  1  1  3
3  R  1  1  1  4
4  R  1  1  1  5

     0  1  2  3  4
0    B  1  1  1  1
1    R  1  1  1  2
2    R  1  1  1  3
3    R  1  1  1  4
4    R  1  1  1  5
5    R  1  1  2  1
6    R  1  1  2  2
7    R  1  1  2  3
8    R  1  1  2  4
9    R  1  1  2  5
10   R  1  1  3  1
11   R  1  1  3  2
12   R  1  1  3  3
13   R  1  1  3  4
14   R  1  1  3  5
15   R  1  1  4  1
16   R  1  1  4  2
17   R  1  1  4  3
18   R  1  1  4  4
19   R  1  1  4  5
20   R  1  1  5  1
21   R  1  1  5  2
22   R  1  1  5  3
23   R  1  1  5  4
24   R  1  1  5  5
25   L  1  2  1  1
26   B  1  2  1  2
27   R  1  2  1  3
28   R  1  2  1  4
29   R  1  2  1  5
..  .. .. .. .. ..
595  L  5  4  5  1
596  L  5  4  5  2
597  L  5  4  5  3
598  B  5  4  5  4
599  R  5  4  5  5
600  L  5  5  1  1
601  L  5  5  1  2
602  L  5  5  1  3
603  L  5  5  1  4
604  L  5  5  1  5
605  L  5  5  2  1
606  L  5  5  2  2
607  L  5  5  2  3
608  L  5  5  2  4
609  L  5  5  2  5
610  L  5  5  3  1
611  L  5  5  3  2
612  L  5  5  3  3
613  L  5  5  3  4
614  L  5  5  3  5
615  L  5  5  4  1
616  L  5  5  4  2
617  L  5  5  4  3
618  L  5  5  4  4
619  L  5  5  4  5
620  L  5  5  5  1
621  L  5  5  5  2
622  L  5  5  5  3
623  L  5  5  5  4
624  B  5  5  5  5

[625 rows x 5 columns]

In [4]:
# Function to split the dataset 
def splitdataset(balance_data): 
  
    # Seperating the target variable 
    X = balance_data.values[:, 1:5] 
    Y = balance_data.values[:, 0] 
  
    # Spliting the dataset into train and test 
    X_train, X_test, y_train, y_test = train_test_split(  
    X, Y, test_size = 0.3, random_state = 100) 
      
    return X, Y, X_train, X_test, y_train, y_test

In [37]:
# Function to perform training with giniIndex. 
def train_using_gini(X_train, X_test, y_train): 
  
    # Creating the classifier object 
    clf_gini = DecisionTreeClassifier(criterion = "gini", 
            random_state = 100,max_depth=4, min_samples_leaf=5) 
    # Performing training 
    clf_gini.fit(X_train, y_train) 
    return clf_gini

In [43]:
# Function to perform training with entropy. 
def tarin_using_entropy(X_train, X_test, y_train): 
  
    # Decision tree with entropy 
    clf_entropy = DecisionTreeClassifier( 
            criterion = "entropy", random_state = 100, 
            max_depth = 4, min_samples_leaf = 5) 
  
    # Performing training 
    clf_entropy.fit(X_train, y_train) 
    return clf_entropy

In [44]:
# Function to make predictions 
def prediction(X_test, clf_object): 
  
    # Predicton on test with giniIndex 
    y_pred = clf_object.predict(X_test) 
    print("Predicted values:") 
    print(y_pred) 
    return y_pred

In [45]:
# Function to calculate accuracy 
def cal_accuracy(y_test, y_pred): 
      
    print("Confusion Matrix: ", 
        confusion_matrix(y_test, y_pred)) 
      
    print ("Accuracy : ", 
    accuracy_score(y_test,y_pred)*100) 
      
    print("Report : ", 
    classification_report(y_test, y_pred))

In [46]:
# Driver code 
def main(): 
      
    # Building Phase 
    data = importdata() 
    X, Y, X_train, X_test, y_train, y_test = splitdataset(data) 
    clf_gini = train_using_gini(X_train, X_test, y_train) 
    clf_entropy = tarin_using_entropy(X_train, X_test, y_train) 
      
    # Operational Phase 
    print("Results Using Gini Index:") 
      
    # Prediction using gini 
    y_pred_gini = prediction(X_test, clf_gini) 
    cal_accuracy(y_test, y_pred_gini) 
      
    print("Results Using Entropy:") 
    # Prediction using entropy 
    y_pred_entropy = prediction(X_test, clf_entropy) 
    cal_accuracy(y_test, y_pred_entropy)

In [47]:
# Calling main function 
if __name__=="__main__": 
    main()

Dataset Length:  625
Dataset Shape:  (625, 5)
Dataset:     0  1  2  3  4
0  B  1  1  1  1
1  R  1  1  1  2
2  R  1  1  1  3
3  R  1  1  1  4
4  R  1  1  1  5
Results Using Gini Index:
Predicted values:
['L' 'L' 'R' 'L' 'R' 'L' 'R' 'L' 'L' 'L' 'L' 'L' 'R' 'L' 'R' 'R' 'L' 'L'
 'R' 'L' 'R' 'L' 'B' 'L' 'R' 'L' 'L' 'L' 'R' 'L' 'L' 'L' 'R' 'L' 'L' 'L'
 'L' 'R' 'L' 'L' 'R' 'L' 'R' 'L' 'R' 'R' 'L' 'B' 'R' 'L' 'L' 'R' 'L' 'L'
 'R' 'L' 'R' 'R' 'L' 'B' 'L' 'R' 'L' 'L' 'L' 'R' 'R' 'R' 'R' 'L' 'L' 'R'
 'R' 'L' 'R' 'L' 'R' 'R' 'R' 'L' 'R' 'R' 'L' 'R' 'L' 'R' 'R' 'L' 'R' 'L'
 'R' 'R' 'L' 'L' 'L' 'R' 'R' 'L' 'L' 'L' 'R' 'L' 'R' 'R' 'R' 'R' 'R' 'R'
 'L' 'L' 'R' 'L' 'R' 'R' 'L' 'L' 'R' 'R' 'R' 'R' 'L' 'R' 'R' 'L' 'L' 'L'
 'L' 'L' 'L' 'R' 'R' 'R' 'R' 'L' 'R' 'R' 'R' 'L' 'L' 'R' 'L' 'L' 'L' 'R'
 'L' 'L' 'R' 'L' 'R' 'R' 'L' 'L' 'L' 'R' 'R' 'R' 'L' 'R' 'R' 'B' 'R' 'R'
 'B' 'L' 'R' 'R' 'L' 'R' 'R' 'R' 'L' 'R' 'B' 'R' 'L' 'R' 'R' 'L' 'R' 'R'
 'B' 'R' 'R' 'L' 'L' 'R' 'R' 'R']
Confusion Matrix:  [[ 0  3 10]
 [ 2 77  6]
 [ 5  8 77]]
Accuracy :  81.91489361702128
Report :                precision    recall  f1-score   support

           B       0.00      0.00      0.00        13
           L       0.88      0.91      0.89        85
           R       0.83      0.86      0.84        90

    accuracy                           0.82       188
   macro avg       0.57      0.59      0.58       188
weighted avg       0.79      0.82      0.81       188

Results Using Entropy:
Predicted values:
['R' 'L' 'R' 'L' 'R' 'R' 'R' 'L' 'L' 'R' 'R' 'L' 'R' 'L' 'R' 'R' 'R' 'L'
 'L' 'R' 'R' 'R' 'L' 'L' 'R' 'L' 'L' 'L' 'R' 'L' 'R' 'L' 'R' 'L' 'L' 'L'
 'R' 'L' 'B' 'R' 'R' 'L' 'R' 'L' 'R' 'R' 'L' 'L' 'R' 'L' 'L' 'R' 'L' 'L'
 'R' 'L' 'R' 'R' 'L' 'B' 'B' 'R' 'L' 'R' 'R' 'R' 'R' 'R' 'L' 'L' 'L' 'R'
 'R' 'L' 'R' 'L' 'R' 'R' 'R' 'L' 'R' 'R' 'L' 'R' 'L' 'R' 'R' 'L' 'R' 'L'
 'R' 'R' 'L' 'L' 'L' 'R' 'R' 'L' 'R' 'R' 'R' 'L' 'L' 'R' 'R' 'R' 'R' 'R'
 'R' 'L' 'R' 'L' 'R' 'R' 'L' 'B' 'R' 'L' 'R' 'R' 'L' 'R' 'R' 'R' 'L' 'L'
 'L' 'L' 'L' 'R' 'R' 'R' 'R' 'L' 'R' 'R' 'R' 'L' 'L' 'R' 'L' 'R' 'L' 'R'
 'L' 'L' 'R' 'L' 'R' 'R' 'L' 'R' 'L' 'R' 'R' 'R' 'L' 'R' 'R' 'R' 'R' 'R'
 'B' 'L' 'R' 'L' 'R' 'R' 'R' 'R' 'L' 'R' 'L' 'R' 'R' 'R' 'L' 'L' 'L' 'R'
 'B' 'R' 'L' 'L' 'L' 'R' 'R' 'R']
Confusion Matrix:  [[ 0  4  9]
 [ 3 64 18]
 [ 3  9 78]]
Accuracy :  75.53191489361703
Report :                precision    recall  f1-score   support

           B       0.00      0.00      0.00        13
           L       0.83      0.75      0.79        85
           R       0.74      0.87      0.80        90

    accuracy                           0.76       188
   macro avg       0.52      0.54      0.53       188
weighted avg       0.73      0.76      0.74       188

In [11]:
data = importdata()

Dataset Length:  625
Dataset Shape:  (625, 5)
Dataset:     0  1  2  3  4
0  B  1  1  1  1
1  R  1  1  1  2
2  R  1  1  1  3
3  R  1  1  1  4
4  R  1  1  1  5

In [12]:
data[data[0] == 'B']

     0  1  2  3  4
0    B  1  1  1  1
26   B  1  2  1  2
30   B  1  2  2  1
52   B  1  3  1  3
60   B  1  3  3  1
78   B  1  4  1  4
81   B  1  4  2  2
90   B  1  4  4  1
104  B  1  5  1  5
120  B  1  5  5  1
126  B  2  1  1  2
130  B  2  1  2  1
153  B  2  2  1  4
156  B  2  2  2  2
165  B  2  2  4  1
182  B  2  3  2  3
186  B  2  3  3  2
208  B  2  4  2  4
216  B  2  4  4  2
234  B  2  5  2  5
246  B  2  5  5  2
252  B  3  1  1  3
260  B  3  1  3  1
282  B  3  2  2  3
286  B  3  2  3  2
312  B  3  3  3  3
338  B  3  4  3  4
342  B  3  4  4  3
364  B  3  5  3  5
372  B  3  5  5  3
378  B  4  1  1  4
381  B  4  1  2  2
390  B  4  1  4  1
408  B  4  2  2  4
416  B  4  2  4  2
438  B  4  3  3  4
442  B  4  3  4  3
468  B  4  4  4  4
494  B  4  5  4  5
498  B  4  5  5  4
504  B  5  1  1  5
520  B  5  1  5  1
534  B  5  2  2  5
546  B  5  2  5  2
564  B  5  3  3  5
572  B  5  3  5  3
594  B  5  4  4  5
598  B  5  4  5  4
624  B  5  5  5  5